# Generated by Django 5.1 on 2024-10-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adicion', models.CharField(choices=[('sal', 'Sal'), ('salTo', 'Salsa_Tomate'), ('mayo', 'Mayonesa'), ('salRo', 'Salsa_Rosada'), ('salPi', 'Salsa_Piña')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreOrden', models.CharField(max_length=40, null=True)),
                ('Cantidad', models.IntegerField()),
                ('Tipo_Orden', models.CharField(choices=[('pa_ll', 'pa llevar'), ('pa_cm', 'para comer aqui'), ('pa_dm', 'para Domicilio')], max_length=20)),
                ('estado', models.CharField(choices=[('esp', 'En espera'), ('pre', 'En Preparacion'), ('serv', 'Plato Servido')], default='esp', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
