# Generated by Django 5.1 on 2024-10-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='adicion',
            field=models.CharField(choices=[('sal', 'Sal'), ('salTo', 'Salsa_Tomate'), ('mayo', 'Mayonesa'), ('salRo', 'Salsa_Rosada'), ('salPi', 'Salsa_Piña'), ('N', 'Ninguna')], max_length=20),
        ),
    ]
